// 5.Arrays
// Exercícío 1
// Exercícío 2
// Exercícío 3
// Exercícío 4
// Exercícío 5
// Exercícío 6
// Exercícío 7
// Exercícío 8
// Exercícío 9
// Exercícío 10
// Exercícío 11
// Exercícío 12
// Exercícío 13
// Exercícío 14
// Exercícío 15
// Exercícío 16
// Exercícío 17
// Exercícío 18
// Exercícío 19